### ISSUE TITLE
new pandas or whatever?

### ISSUE THREAD

**Issue by daniel-caichac-DHI** [DHI/watobs#10]
Hi @jsmariegaard ,

I just tried running the example notebook with a fresh install of new mikeio and pandas>2  etc.
Got this error :(

![image](https://github.com/user-attachments/assets/17f4738d-c8a6-466c-9612-1666d73956b4)

**Comment by jsmariegaard** [comment]
I just did a clean install of the dev version (git clone + pip install -e .) and test and notebooks. Works fine for me. But I guess you're getting the released version (pip install watobs) - and yes I can confirm that that fails :-( I need to make a new release.

**Comment by jsmariegaard** [comment]
Just did a new release, but upload to PyPI failed. Will look into it one of the next days.

**Comment by jsmariegaard** [comment]
@daniel-caichac-DHI a new version has been released - can you confirm that it is working on your side and then close this issue if so

**Comment by daniel-caichac-DHI** [comment]
* Uninstall watobs
* Install watobs
* Now it works :)
